### ISSUE TITLE
Admin Login: Signup form validation

### ISSUE THREAD

**Issue by kural214** [kd-school-erp/erp-ui#187] opened 2023-03-25 17:26 UTC
1. duplicate user name validation ( case sensitive - validation for login )
2. image upload - size validation (500kb)

**Note:** Need to ensure this in all admin forms.

**Comment by kumaresan-subramani** [comment] 2023-03-28 03:01
closing below ticket since this is duplicate of this ticket

https://github.com/kd-school-erp/erp-ui/issues/143

**Closed** 2023-03-29 15:22 UTC
Labels: enhancement, admin/staff
